### ISSUE TITLE
Carsonbot spams me

### ISSUE THREAD

**Issue by ThomasNunninger** [symfony-tools/carsonbot#214]
Once I provided a small PR for Symfony. Even months afterwards, I get some email notifications like

```
Hey!

I think @{MyUserName} has recently worked with this code. Maybe they can help review this?

Cheers!

Carsonbot
```

Sorry, but from my point of view, tagging me in some PRs is not what I want and is spamming. I'm not a core contributor to Symfony. And this decreases the likelyhood that I provide a bug fix again because then I'll probably get more notifications when something changes in other code areas.

Please provide some process to unsubscribe from being tagged in some random PRs

**Comment by weaverryan** [comment]
This feature wasn't as useful as we had hoped anyways. I'm removing it in #215. Apologies for the spam - but thanks for the contribution 👍
